#ifndef ENUM_WIDGET_H
#define ENUM_WIDGET_H

enum GameWidgetType {
	GAME_WIDGET_MENTAT              = 0,
	GAME_WIDGET_OPTIONS             = 1,
	GAME_WIDGET_STATUS              = 2,
	GAME_WIDGET_PICTURE             = 3,
	GAME_WIDGET_REPAIR_UPGRADE      = 4,
	GAME_WIDGET_BUILD_PLACE         = 5,
	GAME_WIDGET_CANCEL              = 6,
	GAME_WIDGET_UNIT_COMMAND_1      = 7,
	GAME_WIDGET_UNIT_COMMAND_2      = 8,
	GAME_WIDGET_UNIT_COMMAND_3      = 9,
	GAME_WIDGET_UNIT_COMMAND_4      = 10,
	GAME_WIDGET_SCROLL_UP           = 11,
	GAME_WIDGET_SCROLL_RIGHT        = 12,
	GAME_WIDGET_SCROLL_LEFT         = 13,
	GAME_WIDGET_SCROLL_DOWN         = 14,
	GAME_WIDGET_VIEWPORT            = 15,
	GAME_WIDGET_MINIMAP             = 16,
	GAME_WIDGET_VIEWPORT_FALLBACK   = 17,

	GAME_WIDGET_MAX                 = 18,
	GAME_WIDGET_INVALID             = 0xFFFF
};

enum GameWidgetIndex {
	WIDGET_INDEX_MENTAT              = 1,
	WIDGET_INDEX_OPTIONS             = 2,
	WIDGET_INDEX_STATUS              = 3,
	WIDGET_INDEX_PICTURE             = 6,
	WIDGET_INDEX_REPAIR_UPGRADE      = 4,
	WIDGET_INDEX_BUILD_PLACE         = 5,
	WIDGET_INDEX_CANCEL              = 7,
	WIDGET_INDEX_UNIT_COMMAND_1      = 8,
	WIDGET_INDEX_UNIT_COMMAND_2      = 9,
	WIDGET_INDEX_UNIT_COMMAND_3      = 10,
	WIDGET_INDEX_UNIT_COMMAND_4      = 11,
	WIDGET_INDEX_SCROLL_UP           = 39,
	WIDGET_INDEX_SCROLL_RIGHT        = 40,
	WIDGET_INDEX_SCROLL_LEFT         = 41,
	WIDGET_INDEX_SCROLL_DOWN         = 42,
	WIDGET_INDEX_VIEWPORT            = 43,
	WIDGET_INDEX_MINIMAP             = 44,
	WIDGET_INDEX_VIEWPORT_FALLBACK   = 45,

	WIDGET_INDEX_INVALID             = 0xFFFF
};

#endif
